### ISSUE TITLE
Connection kelimesi işe yaramıyor!

### ISSUE THREAD

**Issue by biproberkay** [semihcelikol/JwtTokenWithIdentity#1]
"ConnectionStrings": { "**Connection**": "Server=.\SqlName;Database=DbName;Trusted_Connection=True;MultipleActiveResultSets=true" } 

> A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SNI_PN11, error: 26 - Error Locating Server/Instance Specified)
update database bu tip bir hata veriyor.

**Comment by biproberkay** [comment]
ben Connection kelimesi yerine SqlConnection kelimesini kullandım oldu. 
⁉önerme: Connection kelimesi sql server için bir keyword olabilir mi? çünkü kelimeyi bozunca çalıştı. @semihcelikol

**Comment by semihcelikol** [comment]
Selamlar, connection bir name, yani buraya ahmet, mehmet ya da xyz, yazabilirsiniz. Önemli olan startup.cs içerisinde kullandığınız yerde burada yazana göre çağırmanız.
Benim bu örneğime göre startupda Configuration.GetConnectionString("Connection"); olarak çağırmanız yeterli.

**Comment by semihcelikol** [comment]
Selamlar, connection bir name, yani buraya ahmet, mehmet ya da xyz, yazabilirsiniz. Önemli olan startup.cs içerisinde kullandığınız yerde burada yazana göre çağırmanız.
Benim bu örneğime göre startupda Configuration.GetConnectionString("Connection"); olarak çağırmanız yeterli.
