### ISSUE TITLE
Admin Role nasıl atayabiliyoruz ?

### ISSUE THREAD

**Issue by ozdemiribrahim07** [semihcelikol/JwtTokenWithIdentity#2]
Merhaba,
Uygulamaya ve Sql server'a baktığım zaman kayıt olanlar galiba normal user olarak geliyor. Admin olmayı nasıl ayarlayabiliriz acaba?

**Comment by semihcelikol** [comment]
Merhaba,
UserManager, RoleManager sınıfları yardımıyla ekleyebilirsiniz. Kullanımları bu projede mevcut değil. Bu keywordler ile aramalar yaptığınızda ilgili sonuçlara ulaşabilirsiniz.
Öncelikle identity içinde kullanacağınız rolleri tanımlamalısınız.
Proje ilk yüklendiğinde, admin kullanıcısını otomatik olarak kod ile oluşturabilirsiniz. Proje her yüklendiğinde burası kontrol edilir. O yüzden admin kullanıcısı olup olmadığını kontrol ederek admin kullanıcısı oluşuturabilirsiniz. 
Diğer register olan kullanıcıları ise user rolü tanımlayıp onun altına atabilirsiniz.
